# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-11 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_version_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='summary',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Summary'),
        ),
    ]
