# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-04 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20170311_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='employees_count',
            field=models.CharField(blank=True, choices=[('0-5', '0 - 5'), ('5-10', '5 - 10'), ('10-20', '10 - 20'), ('20-50', '20 - 50'), ('50-200', '50 - 200'), ('200-1000', '200 - 1000'), ('1000+', '1000+')], max_length=10, null=True, verbose_name='Employees Count'),
        ),
    ]
