# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-05 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_duediligencemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
