# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-05 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20170905_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='investor_name',
        ),
    ]
