# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-10 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_investment_investor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=127, unique=True, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=127, null=True, verbose_name='Title')),
                ('button_text', models.CharField(max_length=127, verbose_name='Button Text')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Site Info',
                'verbose_name_plural': 'Site Info',
            },
        ),
    ]
