# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-10 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_siteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='button_text',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Button Text'),
        ),
    ]
