# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-10 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20170910_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='duediligencemessage',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='duediligencemessage',
            name='type',
            field=models.CharField(choices=[('due-diligence', 'Due diligence'), ('consulting', 'Consulting'), ('information', 'Information'), ('project', 'Project'), ('feedback', 'Feedback')], default='due-diligence', max_length=31, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
